version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: house_catalog
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    environment:
      USERID: "1000"
      GROUPID: "1000"
    ports:
      - "139:139"
      - "445:445"
    command: >
      -u "sambauser;sambapass"
      -s "uploads;/uploads;yes;no;no;sambauser"
    volumes:
      - ./backend/uploads:/uploads

volumes:
  db_data:
  uploads_data: